---
title: "data_aggregationFP"
author: "Brianne Smith"
date: "2025-03-12"
output: pdf_document
---


```{r}
recieving_data<- read.csv(file = "c://Users//bsket//Documents//UVIC//UVIC Spring 2025//Stat321//finalproject//nfl_receiving_data.csv",header = TRUE)
print(recieving_data)
```
```{r}
wr_salary<- read.csv(file = "c://Users//bsket//Documents//UVIC//UVIC Spring 2025//Stat321//finalproject//nfl_salary_wr.csv", header = TRUE)
#remove team column from salary table
wr_salary<- wr_salary[-c(2)]
wr_salary<- na.omit(wr_salary$Player, wr_salary$Salary)
wr_salary<- na.omit(wr_salary)
wr_salary
```
```{r}
te_salary <- read.csv(file = "c://Users//bsket//Documents//UVIC//UVIC Spring 2025//Stat321//finalproject//nfl_salary_te.csv", header = TRUE)
#remove team column from salary table
te_salary<- te_salary[-c(2)]
#remove na vals
te_salary<- na.omit(te_salary)
te_salary

```

```{r}
#combine the two salary dataframes
all_players_salary<- rbind(wr_salary, te_salary)
all_players_salary
```
```{r}

nrow(all_players_salary)
#remove duplicates
all_players_salary<- all_players_salary[!duplicated(all_players_salary),]
all_players_salary
nrow(all_players_salary)
```


```{r}
#merge the player data dataframe with the salary dataframe, but keep all players data
total_data<- merge(recieving_data, all_players_salary, by= "Player", all.x = TRUE)
total_data

```

```{r}
#new column for catch rate
total_data$catchRate <- (total_data$Rec/ total_data$Tgts)
total_data
```
```{r}
#remove LNG column
total_data<- total_data[-c(7)]
total_data

```
```{r}
#plays between 20-39 yds.
total_data$X20.39<- total_data$X20.- total_data$X40.
total_data
```
```{r}
#remove players with less than 25 receptions
total_data1<- total_data[total_data$Rec >= 25,]
total_data1

```
```{r}
#check how many players we lose if no salary, total_data1 still has NA salary vals
total_data2<- na.omit(total_data1)
total_data2
```

```{r}
total_data1[order(total_data1$Rec, decreasing = TRUE),]

```
